In [2]:
# 定义简单线性回归类
import torch
import torch.nn as nn

class LinearModel(nn.Module):
    def __init__(self,ndim):
        super(LinearModel,self).__init__()
        #初始化
        self.ndim = ndim #输入特征维度的大小
        #使用nn.Parameter来包装这些参数，使之称为子模块（仅仅由参数构成的子模块）
        #因为后续训练的时候需要对参数进行优化，只有将张量转换为参数才能在后续的优化中被优化器访问到

        #weight,bias 为模型的参数
        self.weight = nn.Parameter(torch.randn(ndim,1))
        self.bias = nn.Parameter(torch.randn(1))
    
    def forward(self,x):
        #y = Wx+b
        return x.mm(self.weight)+self.bias


In [3]:
#定义线性回归模型的一个实例
lm = LinearModel(5)
x = torch.randn(4,5)#定义模型的输入
lm(x) #根据模型得到输入对应的输出

tensor([[ 0.3906],
        [-0.6237],
        [ 0.9356],
        [-2.6978]], grad_fn=<AddBackward0>)

In [4]:
#获取模型参数（带名字）的生成器
lm.named_parameters()

<generator object Module.named_parameters at 0x7fe744b67850>

In [5]:
#转换生成器为列表
list(lm.named_parameters())

[('weight',
  Parameter containing:
  tensor([[ 0.8376],
          [ 0.8025],
          [ 0.0091],
          [-0.6313],
          [-0.7149]], requires_grad=True)),
 ('bias',
  Parameter containing:
  tensor([0.3531], requires_grad=True))]

In [6]:
#获取模型参数（不带名字）的生成器
lm.parameters()

<generator object Module.parameters at 0x7fe3b091c150>

In [7]:
#转换生成器为列表显示
list(lm.parameters())

[Parameter containing:
 tensor([[ 0.8376],
         [ 0.8025],
         [ 0.0091],
         [-0.6313],
         [-0.7149]], requires_grad=True),
 Parameter containing:
 tensor([0.3531], requires_grad=True)]

In [17]:
#将模型参数移到GPU上
lm.cuda()

LinearModel()

In [18]:
#将模型参数移到GPU上
#因为服务器有多个GPU，我没有指定具体设备
lm.to(device="cuda")

LinearModel()

In [20]:
#显示模型参数，可以看到已经转移到GPU上了
list(lm.parameters())

[Parameter containing:
 tensor([[ 0.8376],
         [ 0.8025],
         [ 0.0091],
         [-0.6313],
         [-0.7149]], device='cuda:1', requires_grad=True),
 Parameter containing:
 tensor([0.3531], device='cuda:1', requires_grad=True)]

In [21]:
'''float方法会转换所有的参数为单精度浮点数
half方法会转换所有的参数为半精度浮点数
double方法会转换所有的参数为双精度浮点数'''

'float方法会转换所有的参数为单精度浮点数\nhalf方法会转换所有的参数为半精度浮点数\ndouble方法会转换所有的参数为双精度浮点数'

In [22]:
#转换模型参数为半精度浮点数
lm.half()

LinearModel()

In [23]:
#显示模型参数
list(lm.parameters())

[Parameter containing:
 tensor([[ 0.8374],
         [ 0.8022],
         [ 0.0091],
         [-0.6313],
         [-0.7148]], device='cuda:1', dtype=torch.float16, requires_grad=True),
 Parameter containing:
 tensor([0.3530], device='cuda:1', dtype=torch.float16, requires_grad=True)]